### PR TITLE
Remove support for the v1 launch pattern

### PR DESCRIPTION
**Pull request by berroar**
### What is the context of this PR?

We are removing support for the formerly deprecated v1 launch pattern in runner. Updated the documentation to remove references to the v1 launch pattern and have removed the old example files. At present, only the v2 launch pattern will be supported, but naming conventions using v2 will be kept as we may need to support other launch patterns in future.

### Checklist

* [ ] Changes to the spec have been added to example schemas in [examples/](examples/)
* [ ] JSON Schema definitions have been updated

### CODE REVIEW

**Review by Jon-Kent — APPROVED** [review]

**Comment by VirajP1002** [comment]
Looks great so far! I did notice a reference on line 55 `electronic_questionnaire_runner_to_downstream.md` to v1 and since it references a v1 docs that's been deleted, should this be removed?

**Comment by berroar** [comment]
> Looks great so far! I did notice a reference on line 55 `electronic_questionnaire_runner_to_downstream.md` to v1 and since it references a v1 docs that's been deleted, should this be removed?
> 
> Screenshot 2024-04-10 at 15 45 56

Removed now 👍

**Review by VirajP1002 — APPROVED** [review]
Changes look good! 🎉

**Review by pricem14pc — APPROVED** [review]
Aligns with RASRM usage and understanding of the launch claims versions.

**Pull request merged**
