### PR TITLE
Remove the use of readthedocs.org and move to Markdown docs

### PR DESCRIPTION
**Pull request by MebinAbraham**
### Context

Sphinx was used to generate docs for readthedocs.org but it has been decided by the TLs that since we do not use it, it should be removed.

- Removes the Sphinx documents in favour of Markdown. 
- Publishing to readthedoc.org has also been removed (last push was 2 years ago). 
- Certain formats could not be achieved in Markdown, so have been converted to accordingly, i.e. md tables.
- The python dependencies have been removed including the submission schema JSON validation. JSON schema validation need rework and has been reimplemented in #70  
- Updated the CODEOWNERS files to link teams to their respective docs.
- Other changes that have already taken effect: the `main` branch has become the previous `v3` branch. The contents of the old `main` branch are hosted under the `v2-legacy` branch.

### How to review

Ensure the new Markdown documents reflect the same information as the previous RST docs and that all references have been updated.

### CODE REVIEW

**Review by insacuri — APPROVED** [review]
This change looks good to me.  Once it's merged in, I assume the old version that's in readthedocs.org need to be removed?

**Comment by insacuri** [comment]
Not sure why it's having my approval be on behalf of ONSdigital/eq... feel free to dismiss my approval if it wasn't meant for me to approve it!

**Comment by MebinAbraham** [comment]
> This change looks good to me. Once it's merged in, I assume the old version that's in readthedocs.org need to be removed?

I planned to keep it while the `v2-legacy` branch lives on, as it is publishing that branch. I'm happy with either options. Will do if there is consensus.

**Comment by MebinAbraham** [comment]
> Not sure why it's having my approval be on behalf of ONSdigital/eq... feel free to dismiss my approval if it wasn't meant for me to approve it!

Think you are still part of the original eQ team. All reviews are welcome.
The CODEOWNERS file with the correct teams have been updated as part of https://github.com/ONSdigital/ons-schema-definitions/blob/remove-readthedoc-and-use-md/.github/CODEOWNERS

**Review by rmccar — APPROVED** [review]

**Review by berroar — APPROVED** [review]

**Review by petechd — APPROVED** [review]

**Comment by insacuri** [comment]
> > This change looks good to me. Once it's merged in, I assume the old version that's in readthedocs.org need to be removed?
> 
> I planned to keep it while the `v2-legacy` branch lives on, as it is publishing that branch. I'm happy with either options. Will do if there is consensus.

That sounds reasonable.  If the docs are still useful and still exist in github then having them remain on readthedocs.org seems like a good idea.

**Review by davidmort — APPROVED** [review]

**Review by pricem14pc — APPROVED** [review]

**Pull request merged**
