### PR TITLE
 Adding Transaction ID to the RRM and SDX payloads

### PR DESCRIPTION
**Pull request by warrenbailey**
Adds the Transaction ID (tx_id) to both the RRM and SDX payloads

### CODE REVIEW

**Comment by ajmaddaford** [comment]
👍

**Comment by dhilton** [comment]
It's a 👍 from me.

**Comment by warrenbailey** [comment]
I've implemented the EQ side of this and it raises some usability issues with a 128bit GUID. Basically when it's displayed on the thank you page it is pretty ugly and due to it's length difficult to read (see attached screen shot). I've spoken to our designer @alexmorris and he's suggested a string of 16 characters string split into 4 chucks, similar to a credit card number.

So the suggestion is to use a 16 character (64bit) hex decimal number instead of a guid. What are everyone's thoughts?

screen shot 2016-07-11 at 08 59 59

**Comment by pricem14pc** [comment]
I wasn't thinking this would be exposed to the respondent? Nev?

**Comment by warrenbailey** [comment]
If we don't display it and the user has an issue, then how do we know which transaction ID relates to the issue?

**Comment by collisdigital** [comment]
Discussing with Nev, we could keep the current format and only show the first half of the GUID to the user, which would almost certainly be unique.

**Comment by collisdigital** [comment]
I'd also suggest tightening up the format specified here. Are you saying this GUID should be a guid version 4 as per (ftp://ftp.rfc-editor.org/in-notes/rfc4122.txt)? In addition do you want the 'dashed' string format to be passed around (and logged) or just the hex values (i.e. 16 characters). The current PR is showing the dashed text representation; we need to be consistent across all systems.

**Comment by warrenbailey** [comment]
We're agreed to use a GUID (version 4) maintaining the dashes ('-') and log it s as tx_id=GUID.

However when displayed to the user only the first 16 characters will be displayed.

**Comment by collisdigital** [comment]
OK, then make sure this is reflected in the PR changes to the .md files here

**Comment by warrenbailey** [comment]
Done

**Comment by collisdigital** [comment]
@warrenbailey I've made it yet more specific

**Comment by ajmaddaford** [comment]
👍

**Comment by dhilton** [comment]
lgtm 👍  Not sure why it's not merged already?

**Pull request merged**
